# Generated by Django 2.2 on 2019-05-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('rte', 'Ready To Eat'), ('rtd', 'Ready To Drink')], default='rte', max_length=3)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('pic', models.FileField(upload_to='images/')),
            ],
        ),
    ]
