# Generated by Django 3.0.5 on 2021-02-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('master_total', models.FloatField(null=True)),
                ('master_quantity', models.IntegerField(null=True)),
                ('user', models.CharField(max_length=30)),
                ('pic', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('user', models.CharField(max_length=30)),
                ('pic', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Dispatched', 'Dispatched'), (' ', 'delivered')], default='Pending', max_length=20)),
                ('detail', models.CharField(choices=[(' ', 'pending'), ('Dispatched from Source', 'Dispatched'), ('Reaching Destination', 'reaching'), ('Reached Destination', 'reached'), ('Delivered', 'deliverd')], default='pending', max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('rte', 'Ready To Eat'), ('rtd', 'Ready To Drink')], default='rte', max_length=3)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('pic', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
            ],
        ),
    ]
