# Generated by Django 2.2 on 2019-05-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0005_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pic',
            field=models.CharField(max_length=30),
        ),
    ]
