# Generated by Django 2.2 on 2019-05-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0007_ordertable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Dispatched'), ('2', 'Delivered')], default='0', max_length=2),
        ),
    ]
