# Generated by Django 2.2 on 2019-05-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0008_auto_20190528_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='status',
            field=models.IntegerField(),
        ),
    ]
